# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f6e5f96e4bab8b3bdd2a62713d5e78d6336d47fc07f34d52a322ada0efe17d8677aac67e43c305a97819eeb34f2c17ad2fd49d74ec8fec17e1f3952ee6fda8

test:
  secret_key_base: 8934edf4437d694e3e4a17292dd208c2505a8eb24259392048d69a8249a21d0f8df9b08207ad782d6aec14383b7c83bc84bcc38a950903e7d4e3cc4f97d37769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
